name: Deploy Lambda Functions

on:
  push:
    branches: ["main"]
    paths:
      - "getS3url/**"
      - "store-data/**"
      - "get-data/**"
      - "list-data/**"
      - "deleteS3Object/**"
      - "delete-data/**"

jobs:
  deploy-getS3url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./getS3url
        run: npm install

      - name: Zip Lambda
        working-directory: ./getS3url
        run: zip -r ../getS3url.zip .

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: getS3url
          zip_file: getS3url.zip

  deploy-store-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./store-data
        run: npm install

      - name: Zip Lambda
        working-directory: ./store-data
        run: zip -r ../store-data.zip .

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: store-data
          zip_file: store-data.zip

  deploy-get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./get-data
        run: npm install

      - name: Zip Lambda
        working-directory: ./get-data
        run: zip -r ../get-data.zip .

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: get-data
          zip_file: get-data.zip

  deploy-list-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./list-data
        run: npm install

      - name: Zip Lambda
        working-directory: ./list-data
        run: zip -r ../list-data.zip .

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: list-data
          zip_file: list-data.zip

  deploy-delete-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./delete-data
        run: npm install

      - name: Zip Lambda
        working-directory: ./delete-data
        run: zip -r ../delete-data.zip .

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: delete-data
          zip_file: delete-data.zip

  deploy-delete-s3-object:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./deleteS3Object
        run: npm install

      - name: Zip Lambda
        working-directory: ./deleteS3Object
        run: zip -r ../deleteS3Object.zip .

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: deleteS3Object
          zip_file: deleteS3Object.zip
