name: Deploy Lambda

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Zip Lambda
        run: zip -r function.zip .

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          function_name: GETS3URL_GIT
          zip_file: function.zip
