name: Deploy Lambda Functions

on:
  push:
    branches: ["main"]
    paths:
      - "getS3url/**"
      - "store-data/**"

jobs:
  deploy-getS3url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (getS3url)
        working-directory: ./getS3url
        run: npm install

      - name: Zip getS3url Lambda
        working-directory: ./getS3url
        run: zip -r ../getS3url.zip .

      - name: Deploy getS3url Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          function_name: getS3url # <-- put the exact AWS Lambda name here
          zip_file: getS3url.zip

  deploy-store-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies (store-data)
        working-directory: ./store-data
        run: npm install

      - name: Zip store-data Lambda
        working-directory: ./store-data
        run: zip -r ../store-data.zip .

      - name: Deploy store-data Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          function_name: store-data # <-- put the exact AWS Lambda name here
          zip_file: store-data.zip
